#include "Animal.hpp"

/* --- Coplien ------------------------------------------------------------ */
Animal::Animal(std::string const & name) : _type(name) {
	std::cout	<< *this	<< "is generated by its Default Constructor. [Animal Class]"	<< std::endl;
}

Animal::Animal(Animal const &src) : _type(src.getType()) {
	std::cout	<< *this	<< "is generated by its Copy Constructor. [Animal Class]"	<< std::endl;
}

Animal::~Animal(void) {
	std::cout	<< *this	<< "is destructed by its Default Destructor. [Animal Class]"	<< std::endl;
}

Animal&				Animal::operator=(Animal const &src) {
	if (this != &src) {
		(*this) = src;
	}
	std::cout	<< *this	<< "is generated by its Assignment Operator. [Animal Class]"	<< std::endl;
	return (*this);
}
/* --- Coplien ------------------------------------------------------------ */



/* --- Getters / Setters -------------------------------------------------- */
std::string			Animal::getType(void) const {
	return this->_type;
}
/* --- Getters / Setters -------------------------------------------------- */



/* --- Others ------------------------------------------------------------- */
void				Animal::makeSound(void) const {
	std::cout	<< *this	<< "makes some undistinguishable noises. [Animal Class]"	<<	std::endl;
}
/* --- Others ------------------------------------------------------------- */



/* --- Operators ---------------------------------------------------------- */
std::ostream &		operator<<(std::ostream &o, Animal const &animal) {

	std::cout	<< "["	<< animal.getType()	<< "] ";
	return o;
}
/* --- Operators ---------------------------------------------------------- */
