#include "Cat.hpp"

/* --- Coplien ------------------------------------------------------------ */
Cat::Cat(void) : Animal("Cat") , _brain(new Brain("eating mice")){
	std::cout	<< *this	<< "is generated by its Default Constructor. [Cat class]"	<< std::endl;
}

Cat::Cat(Cat const &src) : Animal(src.getType()) , _brain(new Brain(*src._brain)) {
	std::cout	<< *this	<< "is generated by its Copy Constructor. [Cat class]"	<< std::endl;
	this->_brain->setIdeas("eating birds");
}

Cat::~Cat(void) {
	std::cout	<< *this;
	delete this->_brain;
	std::cout	<< *this	<< "is destructed by its Default Destructor. [Cat class]"	<< std::endl;
}

Cat&		Cat::operator=(Cat const &src) {
	if (this != &src) {
		delete this->_brain;
		this->_brain = new Brain(*src._brain);
		(*this) = src;
	}
	std::cout	<< *this	<< "is generated by its Assignment Operator. [Cat class]"	<< std::endl;
	return (*this);
}
/* --- Coplien ------------------------------------------------------------ */



/* --- Others ------------------------------------------------------------- */
void				Cat::makeSound(void) const {
	std::cout	<< *this	<< ": MIAOU [Cat class]"	<<	std::endl;
}

void				Cat::displayBrain(void) const {
	std::cout	<< "[Cat ";
	this->_brain->readIdeas();
}
/* --- Others ------------------------------------------------------------- */
