#include "Dog.hpp"

/* --- Coplien ------------------------------------------------------------ */
Dog::Dog(void) : Animal("Dog") , _brain(new Brain("eating bones")){
	std::cout	<< *this	<< "is generated by its Default Constructor. [Dog class]"	<< std::endl;
}

Dog::Dog(Dog const &src) : Animal(src.getType()) , _brain(new Brain(*src._brain)) {
	std::cout	<< *this	<< "is generated by its Copy Constructor. [Dog class]"	<< std::endl;
	this->_brain->setIdeas("eating slippers");
}

Dog::~Dog(void) {
	std::cout	<< *this;
	delete this->_brain;
	std::cout	<< *this	<< "is destructed by its Default Destructor. [Dog class]"	<< std::endl;
}

Dog&		Dog::operator=(Dog const &src) {
	if (this != &src) {
		delete this->_brain;
		this->_brain = new Brain(*src._brain);
		(*this) = src;
	}
	std::cout	<< *this	<< "is generated by its Assignment Operator. [Dog class]"	<< std::endl;
	return (*this);
}
/* --- Coplien ------------------------------------------------------------ */



/* --- Others ------------------------------------------------------------- */
void				Dog::makeSound(void) const {
	std::cout	<< *this	<< ": WARF [Dog class]"	<<	std::endl;
}

void				Dog::displayBrain(void) const {
	std::cout	<< "[Dog ";
	this->_brain->readIdeas();
}
/* --- Others ------------------------------------------------------------- */
