#include "Cat.hpp"

/* --- Coplien ------------------------------------------------------------ */
Cat::Cat(void) : Animal("Cat") {
	std::cout	<< *this	<< "is generated by its Default Constructor. [Cat class]"	<< std::endl;
}

Cat::Cat(Cat const &src) : Animal(src.getType()) {
	std::cout	<< *this	<< "is generated by its Copy Constructor. [Cat class]"	<< std::endl;
}

Cat::~Cat(void) {
	std::cout	<< *this	<< "is destructed by its Default Destructor. [Cat class]"	<< std::endl;
}

Cat&		Cat::operator=(Cat const &src) {
	if (this != &src) {
		(*this) = src;
	}
	std::cout	<< *this	<< "is generated by its Assignment Operator. [Cat class]"	<< std::endl;
	return (*this);
}
/* --- Coplien ------------------------------------------------------------ */



/* --- Others ------------------------------------------------------------- */
void				Cat::makeSound(void) const {
	std::cout	<< *this	<< ": MIAOU [Cat class]"	<<	std::endl;
}
/* --- Others ------------------------------------------------------------- */
