#include "Dog.hpp"

/* --- Coplien ------------------------------------------------------------ */
Dog::Dog(void) : Animal("Dog") {
	std::cout	<< *this	<< "is generated by its Default Constructor. [Dog class]"	<< std::endl;
}

Dog::Dog(Dog const &src) : Animal(src.getType()) {
	std::cout	<< *this	<< "is generated by its Copy Constructor. [Dog class]"	<< std::endl;
}

Dog::~Dog(void) {
	std::cout	<< *this	<< "is destructed by its Default Destructor. [Dog class]"	<< std::endl;
}

Dog&		Dog::operator=(Dog const &src) {
	if (this != &src) {
		(*this) = src;
	}
	std::cout	<< *this	<< "is generated by its Assignment Operator. [Dog class]"	<< std::endl;
	return (*this);
}
/* --- Coplien ------------------------------------------------------------ */



/* --- Others ------------------------------------------------------------- */
void				Dog::makeSound(void) const {
	std::cout	<< *this	<< ": WARF [Dog class]"	<<	std::endl;
}
/* --- Others ------------------------------------------------------------- */
