#include "WrongCat.hpp"

/* --- Coplien ------------------------------------------------------------ */
WrongCat::WrongCat(void) : WrongAnimal("WrongCat") {
	std::cout	<< *this	<< "is generated by its Default Constructor. [WrongCat class]"	<< std::endl;
}

WrongCat::WrongCat(WrongCat const &src) : WrongAnimal(src.getType()) {
	std::cout	<< *this	<< "is generated by its Copy Constructor. [WrongCat class]"	<< std::endl;
}

WrongCat::~WrongCat(void) {
	std::cout	<< *this	<< "is destructed by its Default Destructor. [WrongCat class]"	<< std::endl;
}

WrongCat&		WrongCat::operator=(WrongCat const &src) {
	if (this != &src) {
		(*this) = src;
	}
	std::cout	<< *this	<< "is generated by its Assignment Operator. [WrongCat class]"	<< std::endl;
	return (*this);
}
/* --- Coplien ------------------------------------------------------------ */



/* --- Others ------------------------------------------------------------- */
void				WrongCat::makeSound(void) const {
	std::cout	<< *this	<< ": WRONG_MIAOU [WrongCat class]"	<<	std::endl;
}
/* --- Others ------------------------------------------------------------- */
